version: '3.9'

volumes:
  dotLanchesDb:
    name: "dotLanchesDb"

networks:
  dotLanchesNetwork:
    driver: bridge

services:
  db:
    image: postgres:16.3-alpine3.18
    container_name: dotlanches_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dotLanches
    ports:
      - "5432:5432"
    volumes:
      - dotLanchesDb:/var/lib/postgresql/data
    networks:
      - dotLanchesNetwork

  api:
    build: 
      context: .
      dockerfile: ./Adapters/Drivers/DotLanches.Api/Dockerfile
    container_name: dotlanches_api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=dotLanches;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - dotLanchesNetwork
