apiVersion: v1
kind: Service
metadata:
  name: dotlanche-db-svc
  labels:
    app: dotlanche-db
spec:
  type: ClusterIP
  selector:
    app: dotlanche-db
  ports:
    - port: 5432
      targetPort: 5432