apiVersion: v1
kind: PersistentVolume
metadata:
  name: dotlanche-persistent-volume
  labels: 
    app: dotlanche-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce 
  storageClassName: local-storage 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: C:\Users\André\repos\dotlanche\.volumeMount