name: CD
#on:
#  push:
#    branches: 
#      - main
#    tags:
#      - v*
on:
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: us-east-1
  AWS_CLUSTER_NAME: ${{ secrets.AWS_CLUSTER_NAME }}
  MONGODB_ATLAS_CONNECTION_STRING: ${{ secrets.MONGODB_ATLAS_CONNECTION_STRING }}

jobs:   
  deploy_to_aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    # needs: publish_image_dockerhub
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    #- name: Extract metadata (tags, labels) for Docker
    #  id: meta
    #  uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
    #  with:
    #    images: angcostaneto/dotlanches
    
    - name: Echo MONGODB_ATLAS_CONNECTION_STRING
      run: echo ${{ env.MONGODB_ATLAS_CONNECTION_STRING }}

    - name: Set up MongoDB connection string
      run: echo "MONGODB_CONNECTION_STRING=${{ env.MONGODB_ATLAS_CONNECTION_STRING }}" >> $GITHUB_ENV

    - name: Update secrets file
      run: |
        ESCAPED_CONNECTION_STRING=$(printf '%s\n' "${{ secrets.MONGODB_ATLAS_CONNECTION_STRING }}" | sed 's/[.*+?^${}()|[\]\\&]/\\&/g')
        awk '{gsub("{{ MONGO_CONNECTION_STRING }}", "'"${ESCAPED_CONNECTION_STRING}"'"); print}' ./.kubernetes/dotlanche-secrets.yaml > temp.yaml && mv temp.yaml ./.kubernetes/dotlanche-secrets.yaml


    - name: Show dotlanche-secrets.yaml
      run: cat ./.kubernetes/dotlanche-secrets.yaml

    #- name: Replace image in dotlanche-deployment.yaml
    #  run: |
    #      sed -i 's|{{ DOCKER_IMAGE }}|'"${{ steps.meta.outputs.tags }}"'|g' ./.kubernetes/dotlanche-api-deployment.yaml
    #
    #- name: Show dotlanche-deployment.yaml
    #  run: cat ./.kubernetes/dotlanche-api-deployment.yaml
#
    #- name: Deploy to AWS EKS
    #  uses: aws-actions/configure-aws-credentials@v1
    #  with:
    #    aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
    #    aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
    #    aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
    #    aws-region: ${{ env.AWS_REGION }}
#
    #- name: Update kubeconfig for EKS
    #  run: |
    #      aws eks update-kubeconfig --name ${{ env.AWS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
#
    #- name: Generate kubernetes manifests
    #  run: |
    #    kubectl apply -f ./.kubernetes/dotlanche-secrets.yaml
    #    kubectl apply -f ./.kubernetes/dotlanche-api-deployment.yaml
    #    kubectl apply -f ./.kubernetes/dotlanche-api-svc.yaml
    #    kubectl apply -f ./.kubernetes/hpa.yaml